MVCProject_IvanaKasalo/Controllers/GradController.cs
using MVCProject_IvanaKasalo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProject_IvanaKasalo.Controllers
{
    public class GradController : MyController
    {


        //// GET: Grad
        //public ActionResult Index(int id)
        //{
        //    //partial bi trebo bit
        //    Session["idDrzava"] = id;
        //    return View(repo.DohvatiGradoveZaDrzavu(id));
        //}

       [Authorize]
        public ActionResult Ajax(int id)
        {
                       return PartialView("_Ajax",repo.DohvatiGradoveZaDrzavu(id));
        }

        [Authorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.drzave = repo.DohvatiDrzave();           

            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(Grad grad)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    grad.Drzava = repo.GetDrzava(grad.Drzava.Naziv);
                    repo.AddGrad(grad);

                    return RedirectToAction("Index", "Drzava");
                }
                catch
                {
                    return View("Error");
                }
            }
            return View();
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            ViewBag.drzave = repo.DohvatiDrzave();
            return View(repo.DohvatiGrad(id));
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(Grad grad)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    grad.Drzava = repo.GetDrzava(grad.Drzava.Naziv);
                    repo.EditGrad(grad);

                    return RedirectToAction("Index", "Drzava");
                }
                catch
                {
                    return View("Error");
                }
            }
            return View(repo.DohvatiGrad(grad.IDGrad));
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            return View(repo.DohvatiGrad(id));
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                repo.DeleteGrad(id);

                return RedirectToAction("Index", "Drzava");
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

MVCProject_IvanaKasalo/Controllers/KupacController.cs
using MVCProject_IvanaKasalo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MVCProject_IvanaKasalo.Controllers
{
    public class KupacController : MyController
    {
        [Authorize]
        public ActionResult Index(int id)
        {
            
            try
            {
                return View(repo.DohvatiKupceZaGrad(id));
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.GetBaseException().Message;
                return View("Error");

            }
        }



        [Authorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize]
        // GET: Kupac/Create
        public ActionResult Create()
        {
            ViewBag.gradovi = repo.GetGradovi();
            return View();
        }

        [Authorize]
        // POST: Kupac/Create
        [HttpPost]
        public ActionResult Create(Kupac kupac)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    kupac.Grad = repo.GetGrad(kupac.Grad.Naziv);
                    repo.AddKupac(kupac);

                    return RedirectToAction("Index", "Drzava");
                }
                catch (Exception ex)
                {
                    ViewBag.error = ex.GetBaseException().Message;
                    return View("Error");
                }
            }
            return View();


        }

        [Authorize]
        // GET: Kupac/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.gradovi = repo.GetGradovi();
            return View(repo.GetKupac(id));
        }

        // POST: Kupac/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Kupac kupac)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    kupac.Grad = repo.GetGrad(kupac.Grad.Naziv);
                    repo.UrediKupca(kupac);

                    return RedirectToAction("Index", "Drzava");
                }
                catch (Exception ex)
                {
                    ViewBag.error = ex.GetBaseException().Message;
                    return View("Error");
                }
            }
            return View(repo.GetKupac(kupac.IDKupac));
        }

        // GET: Kupac/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            return View(repo.GetKupac(id));
        }

        // POST: Kupac/Delete/5
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                repo.DeleteKupac(id);

                return RedirectToAction("Index", "Drzava");
            }
            catch
            {
               
                return View("Error");
            }
        }
    }
}

MVCProject_IvanaKasalo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title MVC Project</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")



</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>*@
                @Html.ActionLink("AdventureWorksOBP", "Index", "Drzava", new { area = "" }, new { @class = "navbar-brand" })
              
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
            <li>@Html.ActionLink("Države", "Index", "Drzava")</li>
        </ul>
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Države", "Index", "Drzava")</li>
        </ul>*@
                <div class="dropdown">
                    <button class="dropbtn">Država</button>
                    <div class="dropdown-content">
                        @Html.ActionLink("Popis", "Index", "Drzava")
                        @Html.ActionLink("Dodaj", "Create", "Drzava")

                    </div>
                </div>

                <div class="dropdown">
                    <button class="dropbtn">Grad</button>
                    <div class="dropdown-content">
                        @Html.ActionLink("Dodaj", "Create", "Grad")
                       

                    </div>
                </div>

                <div class="dropdown">
                    <button class="dropbtn">Države</button>
                    <div class="dropdown-content">
                        @Html.ActionLink("Dodaj", "Create", "Kupac")
                     

                    </div>
                </div>

                @Html.Partial("_LoginPartial")
            </div>
            </div>
        </div>
   
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Ivana Kasalo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>