MVCProject_IvanaKasalo/Models/Kupac.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCProject_IvanaKasalo.Models
{
    public class Kupac
    {
        public int IDKupac { get; set; }
        [Required]
        [StringLength(50)]
        public string Ime { get; set; }

        [Required]
        [StringLength(50)]
        public string Prezime { get; set; }

        [Required]
        [StringLength(50)]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(25)]
        [Phone]
        public string Telefon { get; set; }


        public Grad Grad { get; set; }
    }
}

MVCProject_IvanaKasalo/Controllers/DrzavaController.cs
using MVCProject_IvanaKasalo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProject_IvanaKasalo.Controllers
{
    public class DrzavaController : MyController
    {
        [Authorize]
        public ActionResult Index()
        {
            return View(repo.DohvatiDrzave());
        }

        [Authorize]
        // GET: Drzava/Details/5
        public ActionResult DohvatiDrzavu(int id)
        {
            return View(repo.DohvatiDrzavu(id));
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(Drzava drzava)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repo.AddDrzava(drzava);

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View("Error");
                }
            }

            return View();

           
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            return View(repo.DohvatiDrzavu(id));
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(Drzava drzava)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    repo.EditDrzava(drzava);

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View("Error");
                }
            }
            return View(repo.DohvatiDrzavu(drzava.IDDrzava));
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            return View(repo.DohvatiDrzavu(id));
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection )
        {
            try
            {
                repo.DeleteDrzava(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

MVCProject_IvanaKasalo/Controllers/KupacController.cs
using MVCProject_IvanaKasalo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MVCProject_IvanaKasalo.Controllers
{
    public class KupacController : MyController
    {
        [Authorize]
        public ActionResult Index(int id)
        {
            
            try
            {
                return View(repo.DohvatiKupceZaGrad(id));
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.GetBaseException().Message;
                return View("Error");

            }
        }



        [Authorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize]
        // GET: Kupac/Create
        public ActionResult Create()
        {
            ViewBag.gradovi = repo.GetGradovi();
            return View();
        }

        [Authorize]
        // POST: Kupac/Create
        [HttpPost]
        public ActionResult Create(Kupac kupac)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    kupac.Grad = repo.GetGrad(kupac.Grad.Naziv);
                    repo.AddKupac(kupac);

                    return RedirectToAction("Index", "Drzava");
                }
                catch (Exception ex)
                {
                    ViewBag.error = ex.GetBaseException().Message;
                    return View("Error");
                }
            }
            return View();


        }

        [Authorize]
        // GET: Kupac/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.gradovi = repo.GetGradovi();
            return View(repo.GetKupac(id));
        }

        // POST: Kupac/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Kupac kupac)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    kupac.Grad = repo.GetGrad(kupac.Grad.Naziv);
                    repo.UrediKupca(kupac);

                    return RedirectToAction("Index", "Drzava");
                }
                catch (Exception ex)
                {
                    ViewBag.error = ex.GetBaseException().Message;
                    return View("Error");
                }
            }
            return View(repo.GetKupac(kupac.IDKupac));
        }

        // GET: Kupac/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            return View(repo.GetKupac(id));
        }

        // POST: Kupac/Delete/5
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                repo.DeleteKupac(id);

                return RedirectToAction("Index", "Drzava");
            }
            catch
            {
               
                return View("Error");
            }
        }
    }
}

MVCProject_IvanaKasalo/Controllers/RacunController.cs
using MVCProject_IvanaKasalo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProject_IvanaKasalo.Controllers
{
    public class RacunController : MyController
    {
        [Authorize]
        public ActionResult Index(int id)
        {
            ViewBag.komercijalisti = repo.GetGradovi();
            TempData["ID"] = repo.DohvatiRacuneZaKupca(id);

            return View(repo.DohvatiRacuneZaKupca(id));
        }
        


        [Authorize]
        public ActionResult Details(int id)
        {
            return View(repo.DohvatiStavkeZaRacun(id));
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

      
    }
}

MVCProject_IvanaKasalo/Views/Kupac/Create.cshtml
@model MVCProject_IvanaKasalo.Models.Kupac

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Kupac</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">

        @Html.LabelFor(model => model.Grad.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Grad.Naziv, new SelectList(@ViewBag.gradovi), htmlAttributes: new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Drzava")
</div>

MVCProject_IvanaKasalo/Views/Kupac/Delete.cshtml
@model MVCProject_IvanaKasalo.Models.Kupac

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kupac</h4>
    <hr />
    <dl class="dl-horizontal">
               <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "Drzava")
        </div>
    }
</div>

MVCProject_IvanaKasalo/Views/Kupac/Edit.cshtml
@model MVCProject_IvanaKasalo.Models.Kupac

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Kupac</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.HiddenFor(model => model.IDKupac, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.HiddenFor(model => model.IDKupac, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IDKupac, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">

        @Html.LabelFor(model => model.Grad.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Grad.Naziv, new SelectList(@ViewBag.gradovi), htmlAttributes: new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Drzava")
</div>

MVCProject_IvanaKasalo/Views/Kupac/Index.cshtml
@model IEnumerable<MVCProject_IvanaKasalo.Models.Kupac>

@{

    ViewBag.Title = "Index";
}

<h2>Kupci</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefon)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        @Html.HiddenFor(modelItem => item.IDKupac)
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefon)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { @id = item.IDKupac }, new { @class = "btn btn-info" })

                @Html.ActionLink("Računi", "Index", "Racun", new { @id = item.IDKupac }, new { @class = "btn btn-info" })
                @Html.ActionLink("Delete", "Delete", new { @id = item.IDKupac }, new { @class = "btn btn-primary" })
            </td>
        </tr>
    }

</table>